### ISSUE TITLE
При запуске из Jar не понимает русских символов 

### ISSUE THREAD

**Issue by onifent** [onifent/rpg#6]
пределать проверку валидности с регэкса на чтонибудь ещё

**Comment by Izonami** [comment]
Работает если запустить с ключом -Dfile.encoding=cp866

**Comment by onifent** [comment]
а нет идей как починить чтобы оно работало без этого ключа?

**Comment by Izonami** [comment]
я придумал суровый костыль, по другому хз как. Его надо ткнуть в мейн методе

Он в рантайме подгружает чарсет
System.setProperty("file.encoding","cp866");
Field charset = Charset.class.getDeclaredField("defaultCharset");
charset.setAccessible(true);
charset.set(null, null);

**Comment by onifent** [comment]
а что если конвертить кодировку cp866  в UTF-8 в методе получения пользовательского ввода ?

**Comment by onifent** [comment]
я так понял что виндовская консоль не умеет в UTF-8 и фигачит в своей какой то кодировке
сделать метод на проверку кодировки и конвертации в другую, нужную нам кодировку

**Comment by onifent** [comment]
нашел такой вариант 
   String input = null;
        Console console = System.console();
        input = console.readLine();

**Comment by onifent** [comment]
получилось короч! ура
